### ISSUE TITLE
Failure to build on newer compilers

### ISSUE THREAD

**Issue by midicase** [antmicro/zynq-mkbootimage#21]
Newer compilers (I think gcc 10 and newer) will fail on declaring variables in headers. 

```
gcc -Isrc -DMKBOOTIMAGE_VER="\"mkbootimage 2.2-4ee42d7\"" -Wall -Wextra -Wpedantic --std=c11  src/bif.o src/bootrom.o src/common.o src/mkbootimage.o src/arch/common.o src/arch/zynq.o src/arch/zynqmp.o src/file/bitstream.o src/file/elf.o -o mkbootimage -lpcre -lelf
/usr/bin/ld: src/arch/zynqmp.o:(.data.rel.local+0x0): multiple definition of `zynqmp_bops'; src/mkbootimage.o:(.bss+0x0): first defined here
```

bootrom_ops_t zynqmp_bops;
to
extern bootrom_ops_t zynqmp_bops;

in both zynq.h and zynqmp.h is a quick fix.

**Comment by tgorochowik** [comment]
Hi, thanks for the report!

Please make sure to use the current sources, this has been fixed a while ago: #13

**Comment by midicase** [comment]
I thought I was using master, but now i see it.

**Comment by tgorochowik** [comment]
No problem, thanks again!
