### ISSUE TITLE
File path support?

### ISSUE THREAD

**Issue by sergachev** [antmicro/zynq-mkbootimage#22]
A normal bif file containing a path to input file like `[offset=0x0, bootloader] build/boot.bin` causes mkbootimage to complain:
```
mkbootimage 2.3-0f5ba31
error: digilent_zedboard/boot.bif:2:41: expected '}' operator, got '/' operator
```
Xilinx's bootgen supports paths.

**Comment by tgorochowik** [comment]
Thanks for the report! This has been fixed by #23
